spring:
  datasource:
    name: quora
    url: jdbc:mysql://localhost:3306/quora
    username: root
    password: 121314
    driver-class-name: com.mysql.jdbc.Driver


#mybatis的配置
mybatis:
  type-aliases-package: com.xuef.model
  config-location: classpath:/mybatis-config.xml
  #mapper-locations: classpath:mapper/*.xml

#启动的服务监听端口
server:
  port: 80